### ISSUE TITLE
Erro while running the demo scrip

### ISSUE THREAD

**Issue by RECONupm** [Zhuolu-Hou/POS-GIFT#1]
Dear authors, 
thanks so much for the code, seems to be really interesting¡

I wanto to run you demo script howerver when i try to run in matlab i get the following error: 

Not enough input arguments.

Error in DetectAndComputer_GIFT

Error in MultiScale_DetectAndComputer

Error in POS_GIFT_demo (line 24)
[DescriptorForImage1,DescriptorForImage2,eo_gauss1,eo_gauss2] = MultiScale_DetectAndComputer(image1 ...

All the best, 
Luis

**Comment by mouadh92** [comment]
Same issue here :)

**Comment by ZFD1** [comment]
Same issue here :)

**Comment by niaoyu-bit** [comment]
Same situation, it loosk like the code isn't totally completed.
